name: app-ci

on:
  push:
    paths-ignore:
      - 'content/**'
      - '.github/workflows/content-ci.yaml'
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    name: build and pushe the image to ECR
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
      AWS_ACCOUNT_ID: "648835056994"
      ECR_REPO: "devops-blog"

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Show context
        run: |
          echo "repo: $GITHUB_REPOSITORY"
          echo "sha:  $GITHUB_SHA"

      - name: debug role target
        run: echo "ROLE=${{ vars.AWS_ROLE_TO_ASSUME }}"

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: verify AWS identity
        run: aws sts get-caller-identity

      - name: login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and pushw
        id: buildpush
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:sha-${{ github.sha }}
            
      - name: print digest hash
        run: |
            echo "DIGEST=${{ steps.buildpush.outputs.digest }}"
            echo "IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}@${{ steps.buildpush.outputs.digest }}"

      - name: Get github secret from AWS
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            github/devopsblog/github-app, ghapp
          name-transformation: lowercase
          parse-json-secrets: true

      - name: create GitHubApp token
        id: apptoken
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ env.ghapp_app_id }}
          private-key: ${{ env.ghapp_private_key_pem }}
          owner: valentindodovu51
          repositories: devopsblog-gitops

      - uses: actions/checkout@v4
        with:
          repository: valentindodovu51/devopsblog-gitops
          ref: master
          path: gitops
          token: ${{ steps.apptoken.outputs.token }}

      - name: modify dev deployment with the newly built image
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: gitops/dev/devopsblog-dev/deployment.yaml
          propertyPath: "spec.template.spec.containers[0].image"
          value: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}@${{ steps.buildpush.outputs.digest }}
          commitChange: false


      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.apptoken.outputs.token }}
          path: gitops
          base: master
          branch: ci/dev-${{ github.sha }}
          delete-branch: true
          title: "dev: deploy ${{ github.sha }} (digest)"
          body: "Image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}@${{ steps.buildpush.outputs.digest }}"
          commit-message: "dev: deploy ${{ github.sha }} (digest)"