name: app-ci

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "content/**"
      - ".github/workflows/**"
      - "README.md"
concurrency:
  group: gitops-dev-validation
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  build-push-image-to-ecr-and-gitops:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
      AWS_ACCOUNT_ID: "648835056994"
      ECR_REPO: "devops-blog"
      IMAGE_NAME: devops-blog
      IMAGE_TAG: sha-${{ github.sha }}

        
    steps:

      - name: Checkout
        uses: actions/checkout@v6


      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}



      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2



      - name: Build image
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}



      - name: Get GitHub App secret from AWS
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ghapp, github/devopsblog/github-app
          name-transformation: lowercase
          parse-json-secrets: true



      - name: Create GitHub App token
        id: apptoken
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ env.ghapp_app_id }}
          private-key: ${{ env.ghapp_private_key_pem }}
          owner: valentindodovu51
          repositories: devopsblog-gitops



      - name: Checkout GitOps repo
        uses: actions/checkout@v6
        with:
          repository: valentindodovu51/devopsblog-gitops
          ref: master
          path: gitops
          token: ${{ steps.apptoken.outputs.token }}
          persist-credentials: false



      - name: Update dev deployment image with digest as tag
        uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          valueFile: gitops/dev/devopsblog-dev/deployment.yaml
          propertyPath: "spec.template.spec.containers[0].image"
          value: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}@${{ steps.build-push.outputs.digest }}
          commitChange: false

          
      - name: Create PR to gitops repo
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.apptoken.outputs.token }}
          path: gitops
          base: master
          branch: ci/dev-deploy
          delete-branch: true
          title: "dev: deploy ${{ github.sha }} (digest)"
          body: |
            Promoting Main Branch Build to Dev.
            Image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}@${{ steps.build-push.outputs.digest }}
            Tag:   ${{ env.IMAGE_TAG }}
          commit-message: "dev: deploy ${{ github.sha }}"