name: test

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: |
          echo "repo: $GITHUB_REPOSITORY"
          echo "ref:  $GITHUB_REF"
          echo "sha:  $GITHUB_SHA"
