name: content_ci

on:
  push:
    paths:
      - 'content/**'
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
    upload-content:
      name: Upload blog content to S3
      runs-on: ubuntu-latest
      env:
        AWS_REGION: eu-central-1
        AWS_ACCOUNT_ID: "648835056994"
        ECR_REPO: "devops-blog"

      steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: get AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: get GitHubApp creds from aws
        id: ghapp
        run: |
          aws secretsmanager get-secret-value --region "${AWS_REGION}" --secret-id github/devopsblog/github-app --query SecretString --output text > ghapp.json
          echo "app_id=$(jq -r .app_id ghapp.json)" >> "$GITHUB_OUTPUT"
          echo "installation_id=$(jq -r .installation_id ghapp.json)" >> "$GITHUB_OUTPUT"
          echo "private_key<<EOF" >> "$GITHUB_OUTPUT"
          jq -r .private_key_pem ghapp.json >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: create GitHubApp token
        id: apptoken
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ steps.ghapp.outputs.app_id }}
          private-key: ${{ steps.ghapp.outputs.private_key }}
          owner: valentindodovu51
          repositories: devopsblog-gitops

      - name: Upload content to S3 (dev)
        run: |
          aws s3 sync content/ s3://${{ vars.CONTENT_BUCKET }}/dev/ --delete

      - name: Debug token can see gitops repo
        env:
          GH_TOKEN: ${{ steps.apptoken.outputs.token }}
        run: |
          curl -fsSL -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/valentindodovu51/devopsblog-gitops | jq -r .full_name


      - name: Trigger GitOps content validation
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.apptoken.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: "valentindodovu51",
              repo: "devopsblog-gitops",
              workflow_id: "content_validation.yaml",
              ref: "master",
            });


