name: pr-validation

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "content/**"
      - ".github/workflows/**"
      - "README.md"
      - "docs/**"


concurrency:
  group: pr-validation-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  validate-and-package-image:
    runs-on: ubuntu-24.04
    env:
      AWS_REGION: eu-west-1
      IMAGE_NAME: devops-blog
      IMAGE_TAG: SAST-build

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      


      - name: get AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}



      - name: Load scanner tokens
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            github/devopsblog/scanners
          name-transformation: uppercase
          parse-json-secrets: true



      - name: Export tokens
        run: |
          echo "SONAR_TOKEN=$GITHUB_DEVOPSBLOG_SCANNERS_SONAR_GHA_TOKEN" >> $GITHUB_ENV
          echo "SNYK_TOKEN=$GITHUB_DEVOPSBLOG_SCANNERS_SNYK_GHA_TOKEN"   >> $GITHUB_ENV



      - name: Sonar scan step
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.organization=${{ vars.SONAR_ORG_KEY }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.sources=.
            -Dsonar.exclusions=content/**,.github/**,**/*.md,.dockerignore
            -Dsonar.coverage.exclusions=**



      - name: Pass sonar quality gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        timeout-minutes: 5



      - name: Build image to scan
        uses: docker/build-push-action@v6
        with:
            context: .
            push: false
            load: true
            tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            outputs: type=docker



      - name: Snyk SCA (Python 3.12) - fail on High
        uses: snyk/actions/python-3.12@master
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high



      - name: Snyk Container Scan - fail on High
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          args: --severity-threshold=high